name: test_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.9
  google_fonts: 6.1.0
  dartz: 0.10.1
  intl: 0.18.1
  dio: ^4.0.6
  pretty_dio_logger: any
  equatable: 2.0.5
  flutter_dotenv: 5.1.0
  get_storage: 2.1.1
  fluttertoast: 8.2.4
  loading_overlay: 0.3.0
  lottie: 2.7.0
  pull_to_refresh_flutter3: 2.0.2
  awesome_dialog: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svg/
    - assets/lottie/
    - assets/icons/
    - .env
  uses-material-design: true

